version: "3.5"
services:
  kong:
    build: .
    ports:
      - 8080:80
      - 8001
    volumes:
      - ./config:/usr/local/kong/declarative/
        #nexus:
        #  image: sonatype/nexus3:latest

volumes:
  nexus-data: {}

networks:
  default:
    driver: bridge
